- name: "Create timesynd config dir '{{ config_dir_path }}'"
  ansible.builtin.file:
    path: "{{ config_dir_path }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: '755'
  vars:
    config_dir_path: "{{ timesyncd_conf_filepath | dirname }}"
  become: true
  become_user: root

- name: "Create initial timesynd config file '{{ timesyncd_conf_filepath }}'"
  ansible.builtin.template:
    dest: "{{ timesyncd_conf_filepath }}"
    src: "timesyncd.j2"
    owner: 'root'
    group: 'root'
    mode: '644'
    force: no
  become: true
  become_user: root

- name: "Set systemd-timesyncd primary NTP servers"
  ansible.builtin.include_tasks: func/edit_timesync_conf.yml
  vars:
    description: "primary NTP servers"
    setting_line: "NTP={{ primary_ntp_servers }}"

- name: "Set systemd-timesyncd fallback NTP servers"
  ansible.builtin.include_tasks: func/edit_timesync_conf.yml
  vars:
    description: "fallback NTP servers"
    setting_line: "FallbackNTP={{ fallback_ntp_servers }}"

- name: "Start and enable systemd-timesyncd"
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: yes
  become: true
  become_user: root

