- name: "Restart systemd-timesyncd"
  service:
    name: systemd-timesyncd
    state: restarted
  become: true
  become_user: root
  listen: "restart-systemd-timesyncd"

- name: "Restart ntpd"
  service:
    name: ntpd
    state: restarted
  become: true
  become_user: root
  listen: "restart-ntpd"

